language: ruby
rvm:
 - 2.2.0

os: 
  - linux

dist:
  - trusty

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script: 
  - docker run -it -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output -R . **/*.adoc

after_failure:
  - docker logs asciidoc-to-html

after_success:      
  - cd output ; mv docs/README.html index.html ; cp -R ../img img
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1  